### PR TITLE
Make compatible with kitspace.org

### PR DESCRIPTION
**Pull request by kasbah**
Hey, I thought this would be a nice project to put up on [kitspace.org](https://kitspace.org). It does currently require the BOM to also be in the repo. I downloaded it from your release and added it. The only other addition is a small manifest file to make sure we pick up the correct files. 

If you are happy to have it listed, just merge this in. It will keep updating (every 24hrs) with this repo going forward. Here is [a preview of what it would look like](http://add-stacklight.preview.kitspace.org/boards/github.com/kitspace-forks/stacklight-hardware/).

### CODE REVIEW

**Comment by Tyler-Ward** [comment]
Hi Kasbah

kitspace looks like a good soloution for making projects more accessable, I have a few feature/implementation suggestions that I will open as issues on the kitspace repo.

Pre merging this in I will cleanup the readme to make it more usefull for those arriving at the project from its hardware repo or via the kitspace site. Will also convert the BOM to CSV format to make it easier to see the diference with any future updates and to allow the alternate mouser parts numbers for many of the components to also appear. Should get a chance to do that in the next day or two.

**Comment by kasbah** [comment]
Sounds like a plan. I've been working on a tool to help with BOMs called [bom-builder](https://github.com/kitspace/bom-builder) ([more info](https://kitspace.org/bom-builder)). It will spit out the BOM in a CSV format. If you think you'd find it useful I can give you free access to a hosted version. We keep it semi-private as we pay for the Octopart API. Just shoot me an email and I'll send you a link.

**Comment by Tyler-Ward** [comment]
Thanks for the access to the bom builder, it was helpfull and seemed to be working well, I initialy encountered an issue when trying to import csv but excel worked fine, it is likley the same problem as in kitspace/bom-builder#38.

I have updated the BOM using the tool and updated the kitspace.yaml file. The changes are in the feature/kitspace branch, if they work ok at your end I will get them merged in.

**Comment by kasbah** [comment]
Updated preview: http://add-stacklight-3.preview.kitspace.org/boards/github.com/Tyler-Ward/stacklight-hardware/

LGTM

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/tyler-ward/stacklight-hardware/

**Comment by Tyler-Ward** [comment]
awesome, thanks for your help.

**Pull request merged**
